services:
  backend:
    image: backend:latest
    build: ./backend
    networks:
      - app-network
  frontend:
    image: frontend:latest
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network: